name: 'test'

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Check Install
      run: make venv
    - name: Run tests
      run: make test
